// COPYRIGHT (C) HARRY CLARK 2024

// CS1_OOP STUDY MATERIAL

// THIS FILE PERTAINS TOWAARDS THE MAIN FUNCITONALITY OF THIS STUDY
// WHEREBY WE HAVE ESTABLISHED AN ARRAYLIST TO DETERMINE THE SIZE OF A PARTY IN AN RPG

// SUCH IS THE CASE WITH THE PREVIOUS STUDY, THIS STUDY EVOKES THIS USAGE
// OF TYPES TO DISCERN BETWEEN CLASS TERMS

// THIS IS KNOWN AS A GENERIC TYPE AND ALLOWS FOR THE INSTANTIATION OF VARIOUS
// TYPES IRREGARDLESS OF THEIR OUTSTANDING TYPE

// USING OOD, I HAVE BEEN ABLE TO ABSTRACT THE FUNCTIONALITY FROM ONE CLASS TO ANOTHER
// TO INFER ACCESSIBLE READIBILITY

public class Main extends PLAYER
{
    public static void main(String[] args)
    {
        EVALUATE_TEAM_SIZE();
    }
}
