// COPYRIGHT (C) HARRY CLARK 2024

// CS1_OOP STUDY MATERIAL

// THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY SURROUNDING METHODS
// AND THE VARIOUS WAYS BY WHICH OOD ENVOKES THE MEANS OF BEING ABLE 
// TO ACCESS SAID METHODS

import java.util.*;

public interface METHODS 
{
    <T> void ADD_PLAYERS(Class<T> PLAYERS);
    <T> void SET(Class<T> PLAYERS);
}
