/* COPYRIGHT (C) HARRY CLARK 2033 */

/* CS1_OOP PORTFOLIO 8 */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY OF PROVIDING THE STYLES */
/* AND THE PRE-REQUISTIES THAT COME WITH IT SUCH AS CHANGING OF COLOUR */
/* BASED OF USER IO */

/* MORE SPECIFICALLY, THIS FILE FOCUSSES ON THE FUNCTIONALITY BEHIND */
/* THE USE OF A HASHMAP TO STORE AND ALLOCATE DATA TYPES THROUGHOUT OUR PROGRAM */

/* SYSTEM INCLUDES */

import java.io.*;
import java.util.HashMap;

import java.util.ArrayList;

public final class STYLE_COLLECTION
{
    private static HashMap<String, STYLE> STYLE_TYPE;
    private static STYLE DEFAULT;

    /* CONCATENATE A NEW TYPE BASED ON THE HASHED DATA CONTENTS */
    /* THIS WILL EVALUATE A STYLE BASED ON IT'S NAME AND PRE-REQUISITES */

    public STYLE_COLLECTION()
    {
        STYLE_TYPE = new HashMap<String, STYLE>();
    }


}