// COPYRIGHT (C) HARRY CLARK 2024

// CS1_OOP STUDY MATERIAL

// THIS FILE PERTAINS TOWAARDS THE MAIN FUNCITONALITY OF THIS STUDY
// WHEREBY WE HAVE ESTABLISHED AN ARRAYLIST WITH AN ARBITRARY AMOUNT OF INDEXS

// FROM THERE, IT IS A CASE OF ADDING THE CORRESPONDING INDEXS TOGETHER IN THAT
// LIST AND EVALUATING THE SIZE

// USING OOD, I HAVE BEEN ABLE TO ABSTRACT THE FUNCTIONALITY FROM ONE CLASS TO ANOTHER
// TO INFER ACCESSIBLE READIBILITY

public class Main extends AL
{
    public static void main(String[] args)
    {
        AL.ADD_NUMBERS();
        AL.EVALUATE_SIZE();
    }
}
